version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-resource-owner
    ports:
      - "27018:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db/resource-owner

volumes:
  mongo-data:
